### ISSUE TITLE
[QUESTION] Client reconnection

### ISSUE THREAD

**Issue by go4cas** [mpetrunic/fastify-sse-v2#66]
What is the expected bahaviour when I have an active client connection, and the serve restarts? Should the client auto-reconnects?

**Comment by go4cas** [comment]
I assume the following scenarios:

- Server restarts: The server is not aware of previous connections, and therefore the client won't auto-connect.
- Client restarts: The client obviously need to manually reconnect.
- Broken network connection: In this scenario the server is aware of client connections, and will resume. the client will attempt to auto-reconnect, when network is back up.

Is my assumption correct?

**Comment by mpetrunic** [comment]
Afaik, EvenSource in browser will automatically reconnect in case server restarts or internet drops. There is a field `retry` that server can emit to indicate to browser how long to wait before attempting to reconnect. EvenSource in browser should also send lastEventId Query param or header to indicate to server what was the last event it received
