### ISSUE TITLE
Immediate Flushing for `reply.sse`

### ISSUE THREAD

**Issue by BoatsDawn** [mpetrunic/fastify-sse-v2#89]
#### Problem

When calling multiple `reply.sse()` methods:

```javascript
reply.sse({ data: JSON.stringify(data1) });
reply.sse({ data: JSON.stringify(data2) });
reply.sse({ data: JSON.stringify(data3) });
```

The events are buffered and sent together, rather than immediately.

#### Proposal

Introduce a method like `reply.sseFlush()` to explicitly flush each event:

```javascript
reply.sse({ data: JSON.stringify(data1) });
reply.sseFlush();
reply.sse({ data: JSON.stringify(data2) });
reply.sseFlush();
```
or
```javascript
reply.sseFlush({ data: JSON.stringify(data1) });
reply.sseFlush({ data: JSON.stringify(data2) });
```

Is this possible, or can such functionality be added?

**Comment by lucasboleite** [comment]
Hey @mpetrunic, I've just sent a PR for this: https://github.com/mpetrunic/fastify-sse-v2/pull/91
I went with the highWaterMark option, since I think it reaches more usecases with a lower impact to current users.. lemme know what you think!
